version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ec4sql
      MYSQL_DATABASE: ec4sql
    ports:
      - "3306:3306"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/wdir
    ports:
      - "3000:3000"
    links:
      - db
